site:
  title: "Red Hat AI (RHAI) 3.5: New Key Features"
  start_page: rhai-3.5-key-features::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
